#!/usr/bin/env bash
# Script that transfers a file from our client to a server
# The file must conform to the folowing requirements:
# The path to the file to be transferred
# The IP of the server we want to transfer the file to
# The username scp connects with
# The path to the SSH private key that scp uses
if [[ "${#@}" -lt 4 ]];
then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
	PATH_TO_FILE="$1"
	IP="$2"
	USERNAME="$3"
	PATH_TO_SSH_KEY="$4"
	scp -i "$PATH_TO_SSH_KEY" \
		-o "StrictHostKeyChecking no" \
		"$PATH_TO_FILE" \
		"$USERNAME@$IP":'~/'"$(echo "$PATH_TO_FILE" | grep -oE '[^/]+' | tail -n1)"
fi
