#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect the below;
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page)
# using curl, it must return a page that contains the string Hello World!
apt-get update
apt-get -y install nginx
ufw alllow 'Nginx HTTP'
web_dir="/var/www/html"
mkdir -p $web_dir
chmod -R 755 /var/www
echo 'Hello World!' > $web_dir/index.html
nginx_config=$(cat << 'EOF'
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		try_files $uri $uri/ =404;
	}
}
EOF
)
bash -c "echo -e '$nginx_config' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ];
then
	service nginx start
else
	service nginx restart
fi
