#!/usr/bin/env bash
# Install, configures and starts the load balancer HAproxy
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script
sudo apt-get update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy
WEBSITE_DOMAIN="thisisteey.tech"
LB_INIT_FILE="/etc/default/haproxy"
LB_CONFIG_FILE="/etc/haproxy/haproxy.cfg"
LB_CONFIGURATION=\
"
#--$WEBSITE_DOMAIN-params-begin--
backend $WEBSITE_DOMAIN-backend
	balance roundrobin
	server 503060-web-01 100.25.199.90:80 check
	server 503060-web-02 52.3.242.186:80 check

frontend $WEBSITE_DOMAIN-frontend
	bind *:80
	mode http
	default_backend $WEBSITE_DOMAIN-backend
#--$WEBSITE_DOMAIN-params-end--
"

[ -f "$LB_INIT_FILE" ] || touch "$LB_INIT_FILE"
[ -f "$LB_CONFIG_FILE" ] || touch "$LB_CONFIG_FILE"

BACKEND_CONFIG=$(grep -Eco "$WEBSITE_DOMAIN-backend" < $LB_CONFIG_FILE)

if [ "$(grep -Eco "^ENABLED=[01]$" < $LB_INIT_FILE)" -gt 0 ];
then
	sed -i "s/^ENABLED=0$/ENABLED=1/" "$LB_INIT_FILE"
else
	echo "ENABLED=1" >> $LB_INIT_FILE
fi

if [ "$BACKEND_CONFIG" -eq 0 ];
then
	echo -e "$LB_CONFIGURATION" >> $LB_CONFIG_FILE
else
	config_start="#--$WEBSITE_DOMAIN-params-begin--"
	config_end="#--$WEBSITE_DOMAIN-params-end--"
	x=$(grep -onE "$config_start" < "$LB_CONFIG_FILE" | cut -d : -f1)
	y=$(grep -onE "$config_end" < "$LB_CONFIG_FILE" | cut -d : -f1)
	x=$((x - 1))
	y=$((y + 1))
	sed -i "$x,$y"d "$LB_CONFIG_FILE"
	echo -en "$LB_CONFIGURATION" >> $LB_CONFIG_FILE
fi

if [ "$(pgrep -c haproxy)" -le 0 ];
then
	service haproxy start
else
	service haproxy restart
fi
