#!/usr/bin/env bash
# Script that configures a server to run and listen on port 80 of all the server's active IPv4 IPs
NGINX_CONFIG="/etc/nginx/sites-enabled/default"
sed -i 's/listen 8080/listen 80/g' "NGINX_CONFIG"
sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' "$NGINX_CONFIG"
pgrep nginx > /dev/null && nginx -s reload
echo '' > /run/nginx.pid
