#!/usr/bin/env bash
# Bash script that creates the file /var/run/myscript.pid containing its PID
cleanup='rm /var/run/myscript.pid; exit $?'
echo $$ > "/var/run/myscript.pid"
trap 'echo "I hate the kill command"; '"$cleanup" SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap ''"$cleanup" SIGQUIT
while true;
do
	echo "To infinity and beyond"
done
