#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely
# With a sleep 2 in between each iteration and
# I am invincible!!! when receiving a SIGTERM signal
while [[ 1 -eq 1 ]];
do
	echo "To infiniy and beyond"
	sleep 2
	trap "echo 'I am invincible!!!'" SIGTERM
done
