#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number in a list format
for dig in {1..100}
do
	if (( dig % 3 == 0 && dig % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( dig % 3 == 0 ))
	then
		echo "Fizz"
	elif (( dig % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$dig"
	fi
done
