#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd using while loop
# Script should only display username, user id, Home directory path for the user
fname="/etc/passwd"
while IFS= read -r lns
do
	echo "$lns" | cut -d ':' -f1,3,6
done < "$fname"
