#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd as a story
fname="/etc/passwd"
f1=""
f2=""
f3=""
while IFS= read -r lns
do
	f1="$(echo "$lns" | cut -d ':' -f1)"
	f2="$(echo "$lns" | cut -d ':' -f4)"
	f3="$(echo "$lns" | cut -d ':' -f6)"
	f4="$(echo "$lns" | cut -d ':' -f7)"
	f5="$(echo "$lns" | cut -d ':' -f3)"
	f6="$(echo "$lns" | cut -d ':' -f2)"
	f7="$(echo "$lns" | cut -d ':' -f5)"
	echo "The user ${f1} is part of the ${f2} gang, lives in ${f3} and rides ${f4}. ${f5}'s place is protected by the passcode ${f6}, more info about the user here ${f7}"
done < "$fname"
