#!/usr/bin/env bash
# Bash script that displays the visitor IP along with the HTTP status code
# Using the while loop and IP HTTP_CODE in a list format
fname="./apache-access.log"
awk '{print $1,$9}' $fname
