#!/usr/bin/env bash
# Bash script that displays Best School 10 times using while loop
# but for the 9th iteration, displays Best School and then Hi on a new line
num=0
while [ $num -lt 10 ]
do
	if [ $num -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( num++ ))
done
