#!/usr/bin/env bash
# Using for loop Bash script that displays the content of the current directory
# In a list format where only the part of the name after the first dash is displayed
currdr=$(ls)
for x in $currdr; do
	echo "$x" | cut -d '-' -f2
done
